version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  pull-request:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test