version: 2.1

orbs:
  node: circleci/node@4.7

executors:
  nodejs:
    docker:
      - image: circleci/node:16.10

workflows:
  master:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - install
      - unit-test:
          requires:
            - install
      - build:
          requires:
            - unit-test
  pull-request:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - install
      - unit-test:
          requires:
            - install
      - build:
          requires:
            - unit-test
      - automerge-lokalise:
          #filters:
          #  branches:
          #    only:
          #      - /^lokalise-[\d|\-|_]+$/
          #requires:
          #  - build
jobs:
  install:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-deps-{{ checksum "package.json" }}
          - node_modules-deps-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-deps-{{ checksum "package.json" }}
  unit-test:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-deps-{{ checksum "package.json" }}
          - node_modules-deps-
      - run:
          name: Run unit test
          command: yarn test
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-deps-{{ checksum "package.json" }}
          - node_modules-deps-
      - run:
          name: Build
          command: yarn build
  automerge-lokalise:
    executor: nodejs
    steps:
      - checkout
      - run: echo "Right before the Git step"
      - run: git --version
      - run: echo "Right before the SSH command"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:yx9UpwgUqnwl7H/zL/eNAW+TTKLvR1MwX06JwTvS4Ho nuria@Nuria"
      - run: echo "Right before the Git command"
      - run:
          name: Automerge branch
          command: |
            git checkout master
            git pull origin master
            git merge test
            git push origin master