version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  pull-request:
    jobs:
      build:
        steps:
          - checkout
          - node/install:
              install-yarn: true
              node-version: '16.10'
          - run: yarn build