version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  pull-request:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:16.10
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.10'
      - run: yarn
      - run: yarn build
      - run: yarn test