version: 2.1

orbs:
  node: circleci/node@4.7

executors:
  nodejs:
    docker:
      - image: circleci/node:16.10

workflows:
  master:
    when:
      equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - install
      - unit-test:
          requires:
            - install
      - build:
          requires:
            - unit-test
  pull-request:
    when:
      not:
        equal: [ master, << pipeline.git.branch >> ]
    jobs:
      - install
      - unit-test:
          requires:
            - install
      - build:
          requires:
            #- lint
            - unit-test
      #- automerge:
      #    filters:
      #      branches:
      #        only:
      #          - /^lokalise-[\d|\-|_]+$/
      #    requires:
      #      - build
jobs:
  install:
    executor: nodejs
    steps:
      - checkout
      - run:
          name: Directory before installing
          command: ls
      - restore_cache:
          keys:
          - node_modules-deps-{{ checksum "package.json" }}
          - node_modules-deps-
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: node_modules-deps-{{ checksum "package.json" }}
      - run:
          name: Directory after installing
          command: ls
  unit-test:
    executor: nodejs
    steps:
      - checkout
      - run:
          name: Directory before getting cache
          command: ls
      - restore_cache:
          keys:
          - node_modules-deps-{{ checksum "package.json" }}
          - node_modules-deps-
      - run:
          name: Directory after getting cache
          command: ls
      - run:
          name: Run unit test
          command: yarn test
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-deps-{{ checksum "package.json" }}
          - node_modules-deps-
      - run:
          name: Build
          command: yarn build
